# Intro to Python: Exercise 1

## Matrix Standardization

The different dimensions or features of a data sample often show different variances. For some subsequent operations, it is a beneficial preprocessing step to standardize the data, i.e. subtract the mean and divide by the standard deviation for each dimension. After this processing, each dimension has zero mean and unit variance. Note that this is not equivalent to data whitening, which additionally de-correlates the dimensions (by means of a coordinate rotation).
Write a function that accepts data matrix x ∈ R<sup>n×d</sup> as input and outputs the same data after normalization. n is the number of samples, and d the number of dimensions, i.e. rows contain samples and columns features.

In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2

Data Generation
===

In [2]:
num_samples, num_features = 10, 5

In [3]:
np.random.seed(10)
data = np.random.rand(num_samples, num_features)

Solution
===

In [4]:
print(data)

[[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701]
 [0.22479665 0.19806286 0.76053071 0.16911084 0.08833981]
 [0.68535982 0.95339335 0.00394827 0.51219226 0.81262096]
 [0.61252607 0.72175532 0.29187607 0.91777412 0.71457578]
 [0.54254437 0.14217005 0.37334076 0.67413362 0.44183317]
 [0.43401399 0.61776698 0.51313824 0.65039718 0.60103895]
 [0.8052232  0.52164715 0.90864888 0.31923609 0.09045935]
 [0.30070006 0.11398436 0.82868133 0.04689632 0.62628715]
 [0.54758616 0.819287   0.19894754 0.8568503  0.35165264]
 [0.75464769 0.29596171 0.88393648 0.32551164 0.1650159 ]]


In [ ]:
def standardize(x):
    ''' fill your code in here...
    '''

    x = (x - np.mean(x, axis=0)) / np.std(x)


    return x

std_data = standardize(data)

In [9]:
print(std_data, "\n\n", np.mean(std_data, axis=0), "\n\n", np.std(std_data, axis=0))

[[ 0.74221514 -1.53123102  0.34284958  0.82708784  0.21697087]
 [-1.25159571 -0.88437118  0.80573805 -1.28772924 -1.2793876 ]
 [ 0.42861569  1.87120061 -1.95440111 -0.03611088  1.36291103]
 [ 0.16290599  1.02614638 -0.90399239  1.44351951  1.00522584]
 [-0.09239894 -1.08827751 -0.60679558  0.55467823  0.01021524]
 [-0.48833587  0.64677955 -0.09679101  0.46808376  0.59102452]
 [ 0.86589732  0.29611837  1.34609788 -0.74004724 -1.27165518]
 [-0.97468739 -1.1911036   1.05436288 -1.73358822  0.68313415]
 [-0.07400565  1.38195824 -1.24301119  1.22125923 -0.31877842]
 [ 0.68138942 -0.52721984  1.25594291 -0.71715299 -0.99966044]] 

 [-1.33226763e-16  8.88178420e-17 -4.44089210e-17 -3.33066907e-17
  2.66453526e-16] 

 [0.68878128 1.13921042 1.08753597 1.02532553 0.89922459]
